### ISSUE TITLE
Add custom datasets as configs

### ISSUE THREAD

**Issue by FANGAreNotGnu** [autogluon/autogluon-bench#15]
Currently adding a multimodal dataset requires:
- Add a datasets class in `object_detection_dataset.py`, `multimodal_dataset.py`, or a new python file.
- Add dataset class names in `"__all__"`
- Add the new python file name (`data_classes`) in `dataset_registry.py` (if applicable).

Ideally, we can provide base dataset classes, and add each custom dataset as a config (.py or .yaml), e.g.

`chestx.py`
```
base_dataset = "ObjectDetectionDataset"
source = "xxx"
dataset_name = "chestx"  # _registry_name = dataset_name
parent_url = "xxx"  # url = parent_url + dataset_name
sha1sum = "xxx"
train_split_name="train"
val_split_name=None
test_split_name="test"
```

**Comment by suzhoum** [comment]
We have added support for this in https://github.com/autogluon/autogluon-bench/pull/43
