### ISSUE TITLE
Add val dataset option for multimodal

### ISSUE THREAD

**Issue by FANGAreNotGnu** [autogluon/autogluon-bench#20]
Currently in `exec.py` only train and test dataset is taken by predictor. We can add a feature to add the `val_data` in `fit_args` if val dataset is available: https://github.com/autogluon/autogluon-bench/blob/94eaa63cec4781cfddba4b9429976533f6d3564a/src/autogluon/bench/frameworks/multimodal/exec.py#L140.

**Comment by suzhoum** [comment]
https://github.com/autogluon/autogluon-bench/pull/30
