### ISSUE TITLE
Aggregating results has error due to pydantic version

### ISSUE THREAD

**Issue by zhiqiangdon** [autogluon/autogluon-bench#39]
Using `agbench aggregate-amlb-results multimodal-benchmark-metrics multimodal image_bench_20230713T182510` encounters the following error:

![image](https://github.com/autogluon/autogluon-bench/assets/25371851/9defd684-102d-420b-98f0-c57c8316c523)

which is due to the new pydantic version is not compatible with ray. Consider pin its version following this PR:
https://github.com/autogluon/autogluon/pull/3370/files

Not sure whether we need to let autogluon-bench use `autogluon.core` as a dependency.

**Comment by suzhoum** [comment]
Updated dependency in https://github.com/autogluon/autogluon-bench/pull/41
